<template>
	<div class="welcome">
		<div class="welcome-logo">
			<img src="/Factory.io-logo.png" alt="app_logo"/>
		</div>
		<div class="welcome-play">
			<div class="welcome-play-button pulsate-bck">
				<button @click="play">PLAY</button>
			</div>
		</div>
	</div>
</template>

<script>
import { useRouter } from "vue-router"
import { defineComponent } from "vue"

export default defineComponent({
	setup() {
		const router = useRouter();

		const play = () => {
			router.push('/login');
		}

		return {
			play,
		}
	}
})
</script>

<style lang="scss">
.pulsate-bck {
	-webkit-animation: pulsate-bck 2s ease-in-out infinite both;
			animation: pulsate-bck 2s ease-in-out infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-10-7 9:51:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
0% {
	-webkit-transform: scale(1);
			transform: scale(1);
}
50% {
	-webkit-transform: scale(0.9);
			transform: scale(0.9);
}
100% {
	-webkit-transform: scale(1);
			transform: scale(1);
}
}
@keyframes pulsate-bck {
0% {
	-webkit-transform: scale(1);
			transform: scale(1);
}
50% {
	-webkit-transform: scale(0.9);
			transform: scale(0.9);
}
100% {
	-webkit-transform: scale(1);
			transform: scale(1);
}
}


.welcome {
	width: 100%;
	height: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	gap: 5rem;
	background-color: rgb(29, 29, 29);

	&-logo {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 400px;
	}

	&-play {
		display: flex;
		align-items: center;
		justify-content: center;
		
		&-button {
			display: flex;
			align-items: center;
			justify-content: center;

			button {
				min-width: 200px;
				padding: 7.5px 10px;
				border-radius: 8px;
				width: fit-content;
				background: rgb(239,228,147);
				background: linear-gradient(90deg, rgba(239,228,147,1) 0%, rgba(210,187,113,1) 51%, rgba(156,112,51,1) 100%);
				color: black;
				font-size: 20px;
			}
		}
	}
}
</style>